Feature 4a workshop
RI-SE/ATOS pull request #143
Opened 2019-10-30 15:15 UTC by sepast

HEAB and MONR implemented according to ISO-spec. (ValueId and ContentLength added)

2019-10-30 15:32 UTC, LukasWikander requested changes
Some small comments, and a heads up that Jenkins will complain about the formatting.

2019-11-19 09:51 UTC, LukasWikander requested changes

2019-11-20 10:52 UTC, sepast reviewed
Perfect!

2019-11-20 12:00 UTC, LukasWikander approved these changes
:+1:

2019-11-20 12:01 UTC, merged