Feature GitHub actions
RI-SE/ATOS pull request #569
Opened 2023-05-08 14:53 UTC by Robert108

This PR adds one build action which is intended to be used as an additional status check for branch protection rule "Minimum number of approved reviews" check that exist today. 
It also modifies the auto version tagging workflow to include build and pushing merged PRs and releases to Docker Hub. 

Additional changes include the possibility to resolve hostnames instead of only numerical IP address for objects. This is needed for users running objects on the same host in which they now can specify "host.docker.internal" instead of the docker bridge gateway ip (which might differ between docker setups) in the VehicleCatalog.xosc

2023-05-09 14:28 UTC, victorjarlow approved these changes
Before merging, implement using hosts own network stack when running via docker compose up

2023-05-09 14:28 UTC, victorjarlow commented on docs/Installation/installation.md
> +docker run --ipc=host --privileged -it -v ~/.astazero/ATOS/:/root/.astazero/ATOS/ -p 80:80 -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 3000:3000 -p 3443:3443 -p 55555:55555 -p 443:443 -p 9090:9090 asta
```suggestion
docker run --network="host" --ipc=host --privileged -it -v ~/.astazero/ATOS/:/root/.astazero/ATOS/ astazero/atos_docker_env:latest bash -c "source /root/atos_ws/install/setup.sh ; ros2 launch atos launch_basic.py"
```

2023-05-09 14:28 UTC, victorjarlow commented on docs/Installation/installation.md
> +You can also start ATOS without the compose file with docker run:
```suggestion
You can also start ATOS without the compose file, using the host's own network stack with docker run:
```

2023-05-09 14:28 UTC, victorjarlow commented on docker-compose.yml
>      command: bash -c "source /root/atos_ws/install/setup.sh ; ros2 launch atos launch_basic.py"
Is there some way of using the hosts networking stack to not have to do these portmappings?

2023-05-09 14:28 UTC, victorjarlow commented on README.md
> +```
```suggestion
docker run --network="host" --ipc=host --privileged -it -v ~/.astazero/ATOS/:/root/.astazero/ATOS/ astazero/atos_docker_env:latest bash -c "source /root/atos_ws/install/setup.sh ; ros2 launch atos launch_basic.py"
```

2023-05-09 14:28 UTC, victorjarlow commented on README.md
> +You can also start ATOS without the compose file with docker run:
```suggestion
You can also start ATOS without the compose file, using the host's own network stack with docker run:
```

2023-05-09 14:50 UTC, Robert108 commented on docs/Installation/installation.md
> +docker run --ipc=host --privileged -it -v ~/.astazero/ATOS/:/root/.astazero/ATOS/ -p 80:80 -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 3000:3000 -p 3443:3443 -p 55555:55555 -p 443:443 -p 9090:9090 asta
I remember now that I tried this and it did not work with the VM of Docker Desktop. It seems like when you specify --network="host" with Docker Desktop the container will use the network stack of the Docker Desktop VM, not the host computer.

2023-05-09 16:52 UTC, victorjarlow commented on docs/Installation/installation.md
> +docker run --ipc=host --privileged -it -v ~/.astazero/ATOS/:/root/.astazero/ATOS/ -p 80:80 -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 3000:3000 -p 3443:3443 -p 55555:55555 -p 443:443 -p 9090:9090 asta
Ok, might be a good idea to update the readme with two alternatives, depending on which version of docker is used.

2023-05-09 17:04 UTC, victorjarlow requested changes
Was a bit premature in approving, we have to understand what we can/cannot do on different docker versions and their underlying network stack implementation

2023-05-29 08:13 UTC, victorjarlow approved these changes

2023-05-29 08:13 UTC, victorjarlow approved these changes

2023-05-31 14:24 UTC, ceciliahernqvist commented
Checked the Docker related stuff, looks good to me!

2023-05-31 14:25 UTC, ceciliahernqvist approved these changes

2023-05-31 14:29 UTC, merged