Feature/configpanel
RI-SE/ATOS pull request #620
Opened 2023-12-20 22:04 UTC by SebastianSvanland

2023-12-22 10:32 UTC, samuelthoren commented
Looks really good, nice work!

Here's a very short review, we can continue reviewing this in January.
- The structure can maybe be improved. Now we have `gui/controlpanel` and `gui/src`, which might be confusing. Maybe we should have a `controlpanel` directory and a `configpanel` directory, and a directory for the shared code or something like that.
- Make it possible to fetch the parameters that are loaded to ATOS, right now it shows the default parameters from the repo.
- Some input about the tabs:
  -  Is it possible to set the default directory that opens when you press `Browse...` to `~/.astazero/ATOS/` instead?
  - When loading for instance an `.xosc`-file, does this it send the full path or only the name? We append `~/.astazero/ATOS/osc/` in EsminiAdapter and if it sends the full path this is not going to work. Maybe a feature that should be added in another PR is to being able to load a scenario file that is located anywhere and not only in `~/.astazero/ATOS/osc/`.
  - I think the integration testing tab is a bit unclear. Is it possible to make it more like the pointcloud tab where you can add and subtract items, and maybe select from pre-defined scenarios?

2024-01-22 13:45 UTC, victorjarlow requested changes

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/public/javascripts/configClient.js
> +    const jsonPlaceholder = loadJsonFile(example);
```suggestion
    const jsonSchema = loadJsonFile(example);
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/views/configpanel.pug
> +script(src='javascripts/configClient.js')
```suggestion
      form#form.well (please wait)
//TODO find out a way to include these from the client javascript file, either by using a cdn or by sending the files from the webserver.
script(src='jsonform/deps/jquery.min.js')
script(src='jsonform/deps/underscore.js')
script(src='jsonform/deps/opt/ace/ace.js')
script(src='jsonform/deps/opt/ace/mode-json.js')
script(src='jsonform/lib/jsonform.js')
script(src='javascripts/configClient.js')
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/public/javascripts/configClient.js
> +            // generateForm(serverResponse.value);
```suggestion
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/public/javascripts/configClient.js
> +    const jsonPlaceholder = loadJsonFile(example);
also on the ones below

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/public/javascripts/configClient.js
> +  // $('#form').jsonForm(createdForm);
```suggestion
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/public/javascripts/configClient.js
> +      //   JSON.stringify(values, null, 2));
```suggestion
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/ros_nodes/config_node.js
> +    // Start the ros2 event loop
```suggestion
//TODO: Currently only journal parameter client implemented..
    this._getParametersSrvMsg = 'rcl_interfaces/srv/GetParameters';
    this._journalGetParametersClient = this._config_node.createClient(this._getParametersSrvMsg, '/atos/journal_control/get_parameters');
    // Start the ros2 event loop
```

2024-01-22 13:45 UTC, victorjarlow commented on gui/src/ros_nodes/config_node.js
> +    if ( !serviceClient.isServiceServerAvailable() || !serviceClient.waitForService(wait_duration_s*1000)) {
```suggestion
  getParamService(serviceClient, ros_parameters, node, ws){
  //TODO: This is not yet tested. Getting parameter values for nodes from ROS2 does not currently work.
    const wait_duration_s = 1 // Wait duration for service to appear in seconds.
    if ( !serviceClient.isServiceServerAvailable() || !serviceClient.waitForService(wait_duration_s*1000)) {
```

2024-01-22 14:02 UTC, victorjarlow approved these changes
Nice!

2024-01-22 14:05 UTC, merged