Make the cmake nicer looking
RI-SE/ATOS pull request #91
Opened 2019-07-08 14:59 UTC by viktorjo

Removed util as a built library and made the linking procedure simpler. Also removed the supervisorcontrol module from the building procedure, since it is not commonly used.

Also changed the name of the program to Maestro and not TEServer :)

2019-07-09 10:49 UTC, LukasWikander requested changes
The runServer.sh script (in repo root dir) should also be updated with the new name of the TEServer executable.

2019-07-15 14:23 UTC, LukasWikander requested changes

2019-07-16 07:06 UTC, konglobemeralt requested changes
Personally I Think that the math library should be named something more descriptive than "m".  
EDIT: When I looked at this the first time I thought m was our meastroMath and not math.h so guess there is nothing we can do

2019-11-14 08:24 UTC, konglobemeralt approved these changes

2020-01-21 12:58 UTC, closed without merging